name: Test workflow

on:
  pull_request_target:

jobs:
  approve: # First step
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo For security reasons, all pull requests need to be approved first before running any automated CI.
  build:
    runs-on: ubuntu-latest
    needs: [approve]
    environment: TEST_ENV
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: print logs
        run : |
          git log --oneline -5
      - name: Check access to secret from PR
        run: echo "${{ secrets.TEST_SECRET }}"

