name: Test workflow

on:
  pull_request_target:

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: TEST_ENV
    steps:
    - name: Check access to secret
      run: echo "${{ secrets.TEST_SECRET }}"

